from molzip.transforms import DeepsmilesTransform, SelfiesTransform, AugmentTransform

all_tests = [
    {
        "dataset": "bbbp",
        "splitter": "scaffold",
        "task": "classification_vec",
        "k": 25,
        "augment": 0,
        "preprocess": False,
        "type_preproc": "default",
        "sub_sample": 0.0,
        "bins": 256,
        "vector": True,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": True,
        "n": 1,
        "result_props": {"augument_n": 0},
    },
    {
        "dataset": "bbbp",
        "splitter": "scaffold",
        "task": "classification",
        "k": 25,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": True,
        "n": 1,
        "result_props": {"augument_n": 0},
    },
    {
        "dataset": "bbbp",
        "splitter": "scaffold",
        "task": "classification_vec",
        "k": 25,
        "augment": 0,
        "preprocess": False,
        "type_preproc": "default",
        "sub_sample": 0.0,
        "bins": 256,
        "vector": True,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": True,
        "n": 1,
        "transforms": [AugmentTransform(1)],
        "result_props": {"augument_n": 1},
    },
    {
        "dataset": "bbbp",
        "splitter": "scaffold",
        "task": "classification",
        "k": 25,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": True,
        "n": 1,
        "transforms": [AugmentTransform(1)],
        "result_props": {"augument_n": 1},
    },
    {
        "dataset": "bbbp",
        "splitter": "scaffold",
        "task": "classification_vec",
        "k": 25,
        "augment": 0,
        "preprocess": False,
        "type_preproc": "default",
        "sub_sample": 0.0,
        "bins": 256,
        "vector": True,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": True,
        "n": 1,
        "transforms": [AugmentTransform(2)],
        "result_props": {"augument_n": 2},
    },
    {
        "dataset": "bbbp",
        "splitter": "scaffold",
        "task": "classification",
        "k": 25,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": True,
        "n": 1,
        "transforms": [AugmentTransform(2)],
        "result_props": {"augument_n": 2},
    },
    {
        "dataset": "bbbp",
        "splitter": "scaffold",
        "task": "classification_vec",
        "k": 25,
        "augment": 0,
        "preprocess": False,
        "type_preproc": "default",
        "sub_sample": 0.0,
        "bins": 256,
        "vector": True,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": True,
        "n": 1,
        "transforms": [AugmentTransform(3)],
        "result_props": {"augument_n": 3},
    },
    {
        "dataset": "bbbp",
        "splitter": "scaffold",
        "task": "classification",
        "k": 25,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": True,
        "n": 1,
        "transforms": [AugmentTransform(3)],
        "result_props": {"augument_n": 3},
    },
    {
        "dataset": "bbbp",
        "splitter": "scaffold",
        "task": "classification_vec",
        "k": 25,
        "augment": 0,
        "preprocess": False,
        "type_preproc": "default",
        "sub_sample": 0.0,
        "bins": 256,
        "vector": True,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": True,
        "n": 1,
        "transforms": [AugmentTransform(4)],
        "result_props": {"augument_n": 4},
    },
    {
        "dataset": "bbbp",
        "splitter": "scaffold",
        "task": "classification",
        "k": 25,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": True,
        "n": 1,
        "transforms": [AugmentTransform(4)],
        "result_props": {"augument_n": 4},
    },
    {
        "dataset": "delaney",
        "splitter": "scaffold",
        "task": "regression",
        "k": 5,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": False,
        "n": 1,
        "result_props": {"augument_n": 0},
    },
    {
        "dataset": "delaney",
        "splitter": "scaffold",
        "task": "regression_vec",
        "k": 5,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": False,
        "n": 1,
        "bins": 256,
        "vector": True,
        "result_props": {"augument_n": 0},
    },
    {
        "dataset": "delaney",
        "splitter": "scaffold",
        "task": "regression",
        "k": 5,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": False,
        "n": 1,
        "transforms": [AugmentTransform(1)],
        "result_props": {"augument_n": 1},
    },
    {
        "dataset": "delaney",
        "splitter": "scaffold",
        "task": "regression_vec",
        "k": 5,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": False,
        "n": 1,
        "bins": 256,
        "vector": True,
        "transforms": [AugmentTransform(1)],
        "result_props": {"augument_n": 1},
    },
    {
        "dataset": "delaney",
        "splitter": "scaffold",
        "task": "regression",
        "k": 5,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": False,
        "n": 1,
        "transforms": [AugmentTransform(2)],
        "result_props": {"augument_n": 2},
    },
    {
        "dataset": "delaney",
        "splitter": "scaffold",
        "task": "regression_vec",
        "k": 5,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": False,
        "n": 1,
        "bins": 256,
        "vector": True,
        "transforms": [AugmentTransform(2)],
        "result_props": {"augument_n": 2},
    },
    {
        "dataset": "delaney",
        "splitter": "scaffold",
        "task": "regression",
        "k": 5,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": False,
        "n": 1,
        "transforms": [AugmentTransform(3)],
        "result_props": {"augument_n": 3},
    },
    {
        "dataset": "delaney",
        "splitter": "scaffold",
        "task": "regression_vec",
        "k": 5,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": False,
        "n": 1,
        "bins": 256,
        "vector": True,
        "transforms": [AugmentTransform(3)],
        "result_props": {"augument_n": 3},
    },
    {
        "dataset": "delaney",
        "splitter": "scaffold",
        "task": "regression",
        "k": 5,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": False,
        "n": 1,
        "transforms": [AugmentTransform(4)],
        "result_props": {"augument_n": 4},
    },
    {
        "dataset": "delaney",
        "splitter": "scaffold",
        "task": "regression_vec",
        "k": 5,
        "augment": 0,
        "preprocess": False,
        "sub_sample": 0.0,
        "is_imbalanced": False,
        "n": 1,
        "bins": 256,
        "vector": True,
        "transforms": [AugmentTransform(4)],
        "result_props": {"augument_n": 4},
    },
]
