
dataset_configs = [
            {
                "dataset": "freesolv",
                "splitter": "random",
                "task": "regression",
                "k": 10,
                "augment": 0,
                "preprocess": True,
                "sub_sample": 0.0,
                "is_imbalanced": True,
                "n": 4,
            },
            {
                "dataset": "delaney",
                "splitter": "random",
                "task": "regression",
                "k": 10,
                "augment": 0,
                "preprocess": True,
                "sub_sample": 0.0,
                "is_imbalanced": True,
                "n": 4,
            },
            {
                "dataset": "lipo",
                "splitter": "random",
                "task": "regression",
                "k": 10,
                "augment": 0,
                "preprocess": True,
                "sub_sample": 0.0,
                "is_imbalanced": True,
                "n": 4,
            },
            # {
            #     "dataset": "sider",
            #     "splitter": "random",
            #     "task": "classification",
            #     "k": 5,
            #     "augment": 0,
            #     "preprocess": False,
            #     "sub_sample": 0.0,
            #     "is_imbalanced": True,
            #     "n": 4,
            # },
            # {
            #     "dataset": "bbbp",
            #     "splitter": "scaffold",
            #     "task": "classification",
            #     "k": 5,
            #     "augment": 0,
            #     "preprocess": False,
            #     "sub_sample": 0.0,
            #     "is_imbalanced": True,
            #     "n": 1,
            # },
            # {
            #     "dataset": "bace_classification",
            #     "splitter": "random",
            #     "task": "classification",
            #     "k": 5,
            #     "augment": 0,
            #     "preprocess": False,
            #     "sub_sample": 0.0,
            #     "is_imbalanced": True,
            #     "n": 4,
            # },
            # {
            #     "dataset": "clintox",
            #     "splitter": "random",
            #     "task": "classification",
            #     "k": 5,
            #     "augment": 0,
            #     "preprocess": False,
            #     "sub_sample": 0.0,
            #     "is_imbalanced": True,
            #     "n": 4,
            # },
            # {
            #     "dataset": "tox21",
            #     "splitter": "random",
            #     "task": "classification",
            #     "k": 5,
            #     "augment": 0,
            #     "preprocess": False,
            #     "sub_sample": 0.0,
            #     "is_imbalanced": True,
            #     "n": 4,
            # },
        ]