all_tests = [
            {
                "dataset": "sampl",
                "splitter": "random",
                "task": "regression",
                "k": 25,
                "augment": 0,
                "preprocess": False,
                "sub_sample": 0.0,
                "is_imbalanced": False,
                "n": 4,
                "vector": False
            },
            {
                "dataset": "sampl",
                "splitter": "random",
                "task": "regression_vec",
                "k": 25,
                "augment": 0,
                "preprocess": False,
                "type_preproc": "default",
                "sub_sample": 0.0,
                "is_imbalanced": False,
                "n": 4,
                "bins": 70,
                "vector": True
            },       
            {
                 "dataset": "delaney",
                 "splitter": "random",
                 "task": "regression",
                 "k": 25,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": False,
                 "n": 4,
            },
           {
                 "dataset": "delaney",
                 "splitter": "random",
                 "task": "regression_vec",
                 "k": 25,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": False,
                 "n": 4,
                "bins": 70,
                "vector": True
            },
            {
                 "dataset": "lipo",
                 "splitter": "random",
                 "task": "regression",
                 "k": 25,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": False,
                 "n": 4,
            },
          {
                 "dataset": "lipo",
                 "splitter": "random",
                 "task": "regression_vec",
                 "k": 25,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": False,
                 "n": 4,
                "bins": 70,
                "vector": True
            },
            {
                 "dataset": "sider",
                 "splitter": "scaffold",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 1,
            },
            {
                 "dataset": "sider",
                 "splitter": "random",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 4,
            },
            {
                 "dataset": "bbbp",
                 "splitter": "scaffold",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 1,
            },
            {
                 "dataset": "bace_classification",
                 "splitter": "scaffold",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 1,
            },
            {
                 "dataset": "bace_classification",
                 "splitter": "random",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 4,
            },
            {
                 "dataset": "clintox",
                 "splitter": "scaffold",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 1,
            },
            {
                 "dataset": "clintox",
                 "splitter": "random",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 4,
            },
            {
                 "dataset": "tox21",
                 "splitter": "scaffold",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 1,
            },
            {
                 "dataset": "tox21",
                 "splitter": "random",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 4,
            },
            {
                 "dataset": "hiv",
                 "splitter": "scaffold",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 1,
            },
            {
                 "dataset": "muv",
                 "splitter": "random",
                 "task": "classification",
                 "k": 5,
                 "augment": 0,
                 "preprocess": False,
                 "sub_sample": 0.0,
                 "is_imbalanced": True,
                 "n": 4,
            },
            {
               "dataset": "schneider",
               "splitter": "random",
                "task": "classification",
                "k": 5,
                "augment": 0,
                "preprocess": True,
                "sub_sample": 0.0,
                "is_imbalanced": False,
                "n": 1,
            },
        ]